### ISSUE TITLE
inconsistent CLI interface for help

### ISSUE THREAD

**Issue by andreineculau** [apex/apex#483] opened 2016-07-12 14:40 UTC
If you have a bug report please let us know the following:

  - __Operating system__: 10.11
  - __Apex Version__: 0.10.2

`apex` does no support `apex -h` nor `apex --help`, but the aws-cli style `apex help` (`aws help`). Except when it comes to commands: `apex build --help`.

Decide on `-h` and `--help`, or just `help`

**Comment by tj** [comment] 2016-07-12 21:39
`apex --help` and `apex -h` work just fine for me? All three work just fine

**Comment by tj** [comment] 2016-07-12 21:39
<img width="511" alt="screen shot 2016-07-12 at 2 39 43 pm" src="https://cloud.githubusercontent.com/assets/25254/16784619/7c5f40c0-483e-11e6-9bb6-da7c9ad6f210.png">

**Comment by tj** [comment] 2016-07-12 21:40
closing as can't reproduce, but feel free to re-open if there's something else weird going on there

**Closed by tj** 2016-07-12 21:40 UTC
