### ISSUE TITLE
EACCES error with golang runtime

### ISSUE THREAD

**Issue by linterpreteur** [apex/apex#593] opened 2016-11-11 08:32 UTC
If you have a bug report please let us know the following:

  - __Operating system__: Windows 10
  - __Apex Version__: 0.10.3

CloudWatch log:
```
START RequestId: 7157f69d-a7e8-11e6-973b-d1e8412f9f97 Version: $LATEST
2016-11-11T08:25:45.905Z	7157f69d-a7e8-11e6-973b-d1e8412f9f97	error: Error: spawn EACCES
END RequestId: 7157f69d-a7e8-11e6-973b-d1e8412f9f97
REPORT RequestId: 7157f69d-a7e8-11e6-973b-d1e8412f9f97	Duration: 26.18 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 5 MB	
Process exited before completing request
```

About the same symptom with #281. If you need more details I'll definitely help. Thanks.

**Comment by clickalicious** [comment] 2016-11-25 00:02
The same behavior for me. Deploying the example from apex 

- Operating system: Windows 10
- Apex Version: 0.11.0

CloudWatch log:
`
23:54:39
START RequestId: 5c648907-b2a1-11e6-954d-a51ebfd7694d Version: $LATEST
23:54:39
2016-11-24T23:54:39.337Z 5c648907-b2a1-11e6-954d-a51ebfd7694d error: Error: spawn EACCES
23:54:39
END RequestId: 5c648907-b2a1-11e6-954d-a51ebfd7694d
23:54:39
REPORT RequestId: 5c648907-b2a1-11e6-954d-a51ebfd7694d Duration: 46.69 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 14 MB
23:54:39
Process exited before completing request`

**Comment by enzo2** [comment] 2016-12-20 22:17
Oddly the lambda was working the day I deployed it, next day this:

`Error: spawn EACCES`

`module initialization error: Error
at exports._errnoException (util.js:870:11)
at ChildProcess.spawn (internal/child_process.js:298:11)
at Object.exports.spawn (child_process.js:362:9)
at Object.<anonymous> (/var/task/index.js:15:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)`

Apex 11.0
Deployed with ubuntu 16.10

**Comment by pmcdowell-okta** [comment] 2017-01-05 00:14
I'm seeing something similar here too.  

- Apex version 0.11.0
- Windows 10

```
{
  "errorMessage": "spawn EACCES",
  "errorType": "Error",
  "stackTrace": [
    "Object.exports.spawn (child_process.js:362:9)",
    "Object.<anonymous> (/var/task/index.js:15:18)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}
```

**Comment by tj** [comment] 2017-01-05 04:31
Hmm I've still never hit this, makes me wonder if it's some intermittent Lambda bug and not Apex specific. I see quite a few references in Google.

**Comment by inge4pres** [comment] 2017-02-21 19:31
Same here on Win10

```
$ go version
go version go1.7.5 windows/amd64

$ apex version
Apex version 0.13.0
```

Cloudwatch Logs
```
module initialization error: Error
at Object.exports.spawn (child_process.js:362:9)
at Object.<anonymous> (/var/task/index.js:15:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```

Happening when Lambda function is triggered via S3 notification.

**Comment by stevedumais** [comment] 2017-04-17 21:11
Seeing the same on my end - did any of you come to some resolution to this problem?

**Comment by linterpreteur** [comment] 2017-04-18 08:25
@stevedumais In my case, no. I had no purpose other than trying the runtime, so I just gave up...

**Comment by tj** [comment] 2017-04-25 22:06
Closing for now. If someone can provide instructions to reproduce let me know.

**Closed by tj** 2017-04-25 22:06 UTC
Labels: can't reproduce

**Comment by fulls1z3** [comment] 2017-09-25 09:34
Instructions: clone the repository and run `apex deploy`, and then test the function on AWS lambda. It fails with the same results mentioned above.

**Comment by NickGlenn** [comment] 2017-10-07 08:01
Been going through this recently and wanted to contribute my findings.  I work on multiple machines, so maybe I can be a lightning rod to help find a solution?

- Windows 10 running `go1.8.3` results in the EACCES error
- macOS Sierra (10.12.4) running `go1.8.1` results in _no errors_
- Linux Bash (4.4.0-43) on Windows 10 running `go1.6.2` results in _no errors_

If I find out more I'll post it here.

**Comment by NickGlenn** [comment] 2017-10-08 00:42
@fulls1z3 Since you've also recently been dealing with this issue, could you please post your OS info and version of `go` that you're using?  I have a theory that I'm working on to hopefully provide a fix for this issue.

**Comment by fulls1z3** [comment] 2017-11-09 11:42
@NickGlenn it was `windows 10` running `go 1.9.1`
