### ISSUE TITLE
Invoking functions locally

### ISSUE THREAD

**Issue by cleung2010** [apex/apex#111] opened 2016-01-20 07:44 UTC
There should be a way to invoke functions locally for testing purposes without having to deploy them. Even though you can't run lambda locally, an invocation could be a simulated after `apex build` on the function and using that compiled function along with the provided `request.json`.

**Comment by mthenw** [comment] 2016-01-20 08:45
We are not planning to include it in apex (vide https://github.com/apex/apex/issues/9). Probably as a separate program simulating because it's a bit hacky. No plans about that separate program yet though.

**Comment by tj** [comment] 2016-01-20 11:02
I have most of a simulator thing built but I'm still contemplating a few UX related changes. Make it build each time is very slow, nice for parity but definitely slow. I was considering skipping builds since we can assume that shimming works as it should. In the case of shimmed languages then you just do `go run main.go < request.json` which is nice haha.. the simulator becomes unnecessary, but we need something for the others

**Comment by tj** [comment] 2016-01-23 20:27
I think out of the things we need to run locally the API gateway stuff is a bigger concern. The main reason I'm not super worried about this is because it encourages just using local invocation instead of writing tests. 

Running apex w/ gateway locally to power a front-end is more valuable I think than just invoking functions locally.

**Comment by cortesi** [comment] 2016-03-07 21:51
Something somewhat related: I have a script that I use to do a "trial" of a function (as opposed to a test) - it deploys the function using a temporary name, invokes it, and then deletes it. This lets me test functions in their deployed environment, and covers things like roles and permissions that I can't test locally with unit tests. Maybe an "apex trial" command that does something similar?

**Comment by tj** [comment] 2016-03-07 22:24
@cortesi I'd use a completely separate account/env personally. We need to add env support soon though for toggling between N accounts.

Unrelated but I'm going to close this for now actually since I think invoking locally is an anti-pattern, it's easy enough to write functions in a way that they are testable and not coupled to Lambda at all.

**Closed by tj** 2016-03-07 22:24 UTC

**Comment by quentinfasquel** [comment] 2017-04-04 07:48
I am facing an issue and having a way to reproduce the AWS Lambda environment locally would be great.

I am having common code for my skill and a server, so the architecture looks like - /app - ... - /skill, long term plan is to move the skill on the server itself but for time restriction purposes and not being sure of what's more efficient I am keeping the skill running on a Lambda. As for the deployment with Apex, I have an apex directory with proper subdirectories and the skill function has an index.js doing the export of the handler, along with symlinks to /app and /skill. Since the code in /skill uses `require('app-root-path')`, the function's index.js contains `require('app-module-path').addPath(__dirname)`. And this is my issue, I am not sure how to make that work on an AWS Lambda.
