### ISSUE TITLE
Reversing the relationship between Apex and Terraform

### ISSUE THREAD

**Issue by neekolas** [apex/apex#462] opened 2016-06-19 21:40 UTC
We are using Apex and Terraform to deploy a reasonably large data processing pipeline (12 functions, 2 docker containers, Elasticache Redis, Mongo) in three environments (development, stage, prod) with two AWS accounts and VPCs (stage & prod, with the development environment living in the stage VPC). Everything communicates via SNS messages and S3 bucket events.

The circular dependencies referenced in #377 make using 'apex infra' pretty unhelpful as described in the docs, even with all the new --env features. But reversing the relationship between Terraform and Apex has been working really well. Here's a simplified version of my Terraform module to build the Lambda functions.

```
resource "template_file" "project_file_template" {
  template = "${file("${path.module}/project.json.tpl")}"
  vars {
    project_name = "${var.project_name}"
    environment = "${var.environment}"
    bucket_name = "${aws_s3_bucket.some_bucket}"
    some_action_topic = "${aws_sns_topic.some_action}"
    function_role = "${aws_iam_role.function_role}"
  }
}

# Perform deployment
resource "null_resource" "apex_deployment" {
    triggers = {
        variables = "${template_file.project_file_template.rendered}"
    }
    provisioner "local-exec" {
        command = "echo '${template_file.project_file_template.rendered}' > /var/task/project.json && cd /var/task && apex deploy --region=${aws.region} --alias ${var.environment}"
    }

    depends_on = ["aws_s3_bucket.some_bucket", "aws_sns_topic.some_action"]
}
```
The project.json.tpl looks like
```
{
  "name": "${project_name}",
  "memory": 256,
  "timeout": 180,
  "runtime": "nodejs4.3",
  "role": "${function_role}",
  "handler": "compiled.default",
  "environment": {
      "bucket_to_put_stuff_into": "${bucket_name}",
      "some_action_topic": "${some_action_topic}"
  },
  "hooks": {
    "build": "compile_code_here",
    "clean": "rm -fr compiled"
  }
}
```

By bringing this into Terraform, Terraform can do what it does best and work out these circular dependencies and provision resources as needed. Here's how I subscribe a function to S3 bucket events, while still making the bucket name available to the functions that need to know where to put items:

```
resource "template_file" "function_arn" {
  template = "arn:aws:lambda:${region}:${account}:function:${var.project_name}_%v:${environment}"
  vars {
    region = "${aws.region}"
    account = "${var.aws_function_account}"
    environment = "${var.environment}"
  }
}

resource "aws_s3_bucket" "some_bucket" {
    bucket = "some_bucket_${var.environment}"
}

resource "aws_lambda_permission" "allow_bucket" {
    statement_id = "AllowExecutionFromHTMLBucket"
    action = "lambda:InvokeFunction"
    function_name = "${format(template_file.function_arn.rendered, "use_some_bucket")}"
    principal = "s3.amazonaws.com"
    source_arn = "${aws_s3_bucket.some_bucket.arn}"

    depends_on = ["null_resource.apex_deployment"]
}

resource "aws_s3_bucket_notification" "bucket_notification" {
    bucket = "${aws_s3_bucket.some_bucket.id}"
    lambda_function {
        lambda_function_arn = "${format(template_file.function_arn.rendered, "use_some_bucket")}"
        events = ["s3:ObjectCreated:*"]
    }

    depends_on = ["null_resource.apex_deployment"]
}
```
Does anyone else think this is a better way of having Apex and Terraform interact. While this does neuter some of the benefits of Apex, Apex still has plenty to offer in packaging the functions, aggregating logs, providing environment variables to functions, and handling function versioning. Am I the only one who would like to see Apex wrapped as a Terraform Provider or plugin?

**Comment by tj** [comment] 2016-06-19 22:18
It's definitely a bit of a problem, and I don't think you're alone, I've seen at least half a dozen similar comments.

For me personally I use apex(1) every day, whereas I use Terraform maybe once a week or often less, so the workflow of "apex first" works out a lot better for me. I also don't want to force people to use Terraform, because it's not yet the clear winner, I think Terraform has a lot of issues to be honest, particularly its relatively poor module system. I think a Terraform-esque tool written in a lisp or similar would be much more powerful.

There's also CloudFormation of course. I want to look into that more as well since a CF option wouldn't have the same issues, since it's highly scriptable. This aspect makes me really wish that Terraform was library-oriented, Apex + TF could have been integrated much nicer I think if it were just a package.

I'm definitely open to suggestions to improve the relationship! But for me at least it's not ideal to have a TF plugin.

**Comment by neekolas** [comment] 2016-06-19 22:41
Ya. Running apex from inside Terraform is definitely the weirdest part for me, as I also spend way more time using Apex than I do using Terraform. And I  haven't made up my mind on whether I really want to put all my eggs in the Terraform basket either.

A middle solution would be to dump all of the generated env vars into a S3 bucket that could be used outside of Terraform. Terraform could still call Apex deploy when needed for bootstrapping a new environment, but in your day-to-day you could just use Apex on its own and download the env vars as part of the build.

The thing that is making me continue to invest time in this is the weirdness of doing local development on functions. When there is a pipeline of things connected via AWS events and services (SNS, SQS), the only sane way to make sure a process works end-to-end is to deploy it somewhere. I am using docker-lambda for basic local dev, and inside CircleCI to do Apex builds in an environment that can compile native dependencies, but it still feels like working in the dark if you can't run it end-to-end. Keeping that dev environment up-to-date with an in-progress project is a PITA, and most of my debugging time seems to be spent tracking down issues with that rather than working on my application code. Being able to spin up and tear down a clean working environment at-will would be a game-changer.

**Comment by tj** [comment] 2016-06-19 22:51
Definitely a tradeoff if your stuff is TF-heavy. I would really love to have apex be standalone and not require anything else for at least a wide-range of use-cases, but that means either going with CloudFormation or custom. I do _really_ think both TF and CF could be much more concise for most of the Lambda use-cases with more logical config, so I'm definitely going to explore that, but I don't want to prevent people from using whatever they like.

Ahh, I've been just testing each function independently with unit tests, the functions themselves are just tiny wrapper around libs. Not including staging for larger scale QA of course! I think in most cases it should be pretty easy to deploy funcs confidently if they have enough tests, but there's also more complex stuff like full-scale stress testing. I don't even go down the road of trying to emulate AWS at all

Anyway if you think of any clever solutions let me know :D.

**Comment by neekolas** [comment] 2016-06-19 23:43
If Apex could manage event source mappings, and expose those resources as env vars (function A needs to know where to send things so function B can receive them) it would be pretty manageable without anything as bulky as CF or Terraform. I'd be fine with handling the initial provisioning of resources in bash scripts or something and just maintaining env-specific project.json files, so long as all the config lives somewhere other than my head and actually lines up with what is on AWS. I kept breaking things doing all the mappings in the AWS console across 3 environments.

I went down the rabbit-hole of trying to forward AWS events to local to test things and that was just a mess. Any testing that involves > 1 function needs to live on AWS. FWIW, running Apex inside [docker-lambda](https://github.com/lambci/docker-lambda/) is fantastic for both local testing and as a test runner/deployment environment inside CircleCI.

**Comment by tj** [comment] 2016-07-03 16:36
Closing for now, not because I think it's wrong, but just because it would be a massive breaking change and it's likely that apex(1) will support no-Terraform setups for a long time including possibly a CloudFormation option as well

**Closed by tj** 2016-07-03 16:36 UTC

**Comment by heri16** [comment] 2017-05-06 13:06
Terraform provider or plugin seems like the best balance of preventing apex from depending on Teraform, while at the same time making things more usable, reproducible, and clear for users. Maybe this plugin/wrapper that resides on the Teraform side could be even a good example for people to fork and adapt as a plugin into whatever infrastructure management tool suits them best. I think we should attempt this.
