### ISSUE TITLE
Doesn't pass through command line vars to terraform with apex infra

### ISSUE THREAD

**Issue by JefStat** [apex/apex#421] opened 2016-05-18 17:10 UTC
using the following command 
```
➜  apex git:(apex_aw_lambda) ✗ apex --env prod infra apply -var 'alias_name=prod'
   ⨯ Error: unknown shorthand flag: 'v' in -var
```

Going directly into the infrastructure directory and using terraform works
```
➜  prod git:(apex_aw_lambda) ✗ terraform apply -var 'alias_name=prod'
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value:
```

**Comment by tj** [comment] 2016-05-18 17:27
Yo! Are you on v0.9.0? I'm not seeing issues:

```
$ apex infra -e prod plan -var foo=bar
Refreshing Terraform state prior to plan
...
```

**Comment by JefStat** [comment] 2016-05-18 17:38
This looks like a duplicate of #350

**Comment by tj** [comment] 2016-05-18 17:50
I think it's different, #350 is caused by the commas. Maybe try a `apex upgrade` first but I can't seem to reproduce with 0.9.0

**Comment by JefStat** [comment] 2016-05-18 17:54
I'm running the latest. 
 ✗ apex upgrade
   • current release is v0.9.0
   • latest release is v0.9.0
   • you're up to date :)

**Comment by tj** [comment] 2016-05-18 18:38
hmm I tried the exact same command and it's fine :( I wonder if maybe there's another apex(1) in your PATH or something

**Comment by samstav** [comment] 2016-05-23 23:33
I'm seeing this issue as well.

```
$ apex --env dev infra plan -var foo=bar
   ⨯ Error: unknown shorthand flag: 'v' in -var
$ apex version
Apex version 0.9.0
$ apex infra --version
Terraform v0.6.16
```

**Comment by samstav** [comment] 2016-05-23 23:37
Oh, but this works:

```
$ apex infra --env dev plan -var foo=bar
```

Just moved the `--env` option behind `apex infra` instead of in-between.

**Comment by JefStat** [comment] 2016-05-24 13:15
thanks will do that.

**Comment by samstav** [comment] 2016-05-24 15:49
@JefStat, still a bug, I think.

**Comment by tj** [comment] 2016-05-25 00:17
Hmm agreed, --env before `infra` should be ok, marking as bug

**Closed** 2016-06-01 03:12 UTC
Labels: bug
