### ISSUE TITLE
Allow invoking functions locally

### ISSUE THREAD

**Issue by chrisseto** [apex/apex#346] opened 2016-03-27 04:43 UTC
There should be a way to run functions without deploying them to lambda.

Ideally `echo '{}' | apex invoke <function> --local` or `echo '{}' | apex run <function>`

**Comment by tj** [comment] 2016-03-27 17:17
Duplicate of #111. Primary reasoning is:

> Unrelated but I'm going to close this for now actually since I think invoking locally is an anti-pattern, it's easy enough to write functions in a way that they are testable and not coupled to Lambda beyond a tiny bit of glue.

Since it's almost impossible to emulate the whole AWS ecosystem locally it would be frail at best IMO. Also it would be quite slow since each `apex invoke <name> --local` would have to build the function first. We may still add it some day but for now I don't think it's a priority.

**Comment by chrisseto** [comment] 2016-03-28 03:58
Ah, sorry to have missed that issue.

I guess what I'm looking for is just a more loose testing harness for functions.

Would you like me to close this issue or do you think there would be value in discussing an `apex test` command or something in that realm?

**Comment by tj** [comment] 2016-03-29 01:18
Always open to suggestions but the local Lambda simulator thing is pretty low priority for now. My functions are typically ~10-15 lines that just connect a few parts, the real logic is in testable modules. I'll close this one for now but feel free to open a new issue if you have ideas

**Closed by tj** 2016-03-29 01:18 UTC
